# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dojo < Formula
  desc "Self-hosted agentic AI CLI powered by the Dojo Genesis gateway"
  homepage "https://github.com/DojoGenesis/cli"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DojoGenesis/cli/releases/download/v1.1.0/dojo_1.1.0_darwin_amd64.tar.gz"
      sha256 "f285491b565a7fd91d1005b8ddbf49ea1b2694d44abdff1cf6b323aa4637e21f"

      define_method(:install) do
        bin.install "dojo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DojoGenesis/cli/releases/download/v1.1.0/dojo_1.1.0_darwin_arm64.tar.gz"
      sha256 "62ba7ed27e070966ef1f82b27e30bc03214ddfd72a3e6ce40fc6f817e27a860b"

      define_method(:install) do
        bin.install "dojo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DojoGenesis/cli/releases/download/v1.1.0/dojo_1.1.0_linux_amd64.tar.gz"
      sha256 "1ac9db7b67ed4842bcfb3990047ad9ae4f6595cc589d700ab3b6c91912e91a09"
      define_method(:install) do
        bin.install "dojo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DojoGenesis/cli/releases/download/v1.1.0/dojo_1.1.0_linux_arm64.tar.gz"
      sha256 "83346c47ac2b99540db02c1216de95ef32d5c07c29e0e32d8cee3b599f760e73"
      define_method(:install) do
        bin.install "dojo"
      end
    end
  end

  test do
    system "#{bin}/dojo", "--version"
  end
end
